import { User, Room, Reservation, ReservationLog, InAppNotification } from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin',
    name: 'Dr. Ir. Budi Santoso, M.Kom',
    email: 'admin@roombook.ac.id',
    password: 'admin123',
    role: 'ADMIN',
    department: 'Bagian Sarana & Prasarana Kampus',
    phone: '0812-3456-7890',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    authProvider: 'EMAIL',
  },
  {
    id: 'usr-dosen',
    name: 'Dr. Maya Anggraini, S.T., M.T.',
    email: 'dosen@roombook.ac.id',
    password: 'dosen123',
    role: 'DOSEN',
    department: 'Departemen Teknik Informatika',
    phone: '0813-9876-5432',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    authProvider: 'EMAIL',
  },
  {
    id: 'usr-mhs1',
    name: 'Rizky Pratama (Ketua BEM)',
    email: 'mahasiswa@roombook.ac.id',
    password: 'mhs123',
    role: 'MAHASISWA',
    department: 'Badan Eksekutif Mahasiswa (BEM)',
    phone: '0857-1122-3344',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    authProvider: 'EMAIL',
  },
  {
    id: 'usr-staf',
    name: 'Hendra Gunawan, S.AP.',
    email: 'staf@roombook.ac.id',
    password: 'staf123',
    role: 'STAF',
    department: 'Biro Administrasi Akademik & Kemahasiswaan',
    phone: '0819-5566-7788',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    authProvider: 'EMAIL',
  },
  {
    id: 'usr-gcp',
    name: 'Sarah Wijaya, S.Kom (GCP SSO)',
    email: 'sarah.wijaya@campus.ac.id',
    role: 'DOSEN',
    department: 'Google Cloud Computing Lab & Informatika',
    phone: '0811-2233-4455',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    authProvider: 'GCP_GOOGLE',
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-auditorium',
    name: 'Auditorium Utama Graha Wiyata',
    building: 'Gedung Rektorat Lt. 3',
    floor: 3,
    capacity: 250,
    facilities: ['Proyektor 4K Laser', 'Sound System 5000W', 'AC Central', 'Podium & 4 Mic Wireless', 'Lighting Panggung'],
    status: 'ACTIVE',
    openingHour: '08:00',
    closingHour: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
    description: 'Ruangan serbaguna skala besar untuk seminar nasional, simposium ilmiah, kuliah tamu, dan pelantikan organisasi mahasiswa.',
  },
  {
    id: 'room-lab-ai',
    name: 'Laboratorium Riset AI & Komputer Terpadu',
    building: 'Gedung Sains & Teknologi Lt. 2',
    floor: 2,
    capacity: 45,
    facilities: ['45 PC Workstation i7 RTX 4070', 'Dual Proyektor HD', 'AC Split 3 Unit', 'Gigabit LAN', 'Whiteboard Kaca'],
    status: 'ACTIVE',
    openingHour: '08:00',
    closingHour: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80',
    description: 'Ruang komputasi berkecepatan tinggi cocok untuk workshop pemrograman, pelatihan data science, dan sertifikasi IT.',
  },
  {
    id: 'room-smart-class',
    name: 'Smart Classroom & Hybrid Studio 101',
    building: 'Gedung Perkuliahan Bersama Lt. 1',
    floor: 1,
    capacity: 60,
    facilities: ['Interactive Smart Board 85 Inch', 'Kamera Hybrid Auto-Tracking', 'Sound Ceiling', 'AC Central', 'Meja Kursi Fleksibel'],
    status: 'ACTIVE',
    openingHour: '08:00',
    closingHour: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80',
    description: 'Ruang kelas modern dengan fasilitas pembelajaran interaktif dan siaran langsung kuliah hibrida.',
  },
  {
    id: 'room-rapat-senat',
    name: 'Ruang Rapat Senat & Eksekutif',
    building: 'Gedung Rektorat Lt. 2',
    floor: 2,
    capacity: 30,
    facilities: ['Smart TV 75 Inch 4K', 'Sistem Video Conference Polycom', 'Mic Meja Delegate 20 Unit', 'AC Central', 'Dispenser & Minibar'],
    status: 'ACTIVE',
    openingHour: '08:00',
    closingHour: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    description: 'Ruang rapat representatif khusus pimpinan, dewan pertimbangan, dan koordinasi antar fakultas.',
  },
  {
    id: 'room-aula-student',
    name: 'Aula Kemahasiswaan & Seni',
    building: 'Gedung Student Center Lt. 1',
    floor: 1,
    capacity: 120,
    facilities: ['Panggung Portable', 'Sound System 2000W', 'Proyektor HD', 'Kipas Angin Turbin & AC', 'Lantai Parquet Karpet'],
    status: 'ACTIVE',
    openingHour: '08:00',
    closingHour: '20:00',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    description: 'Pusat aktivitas ormawa untuk latihan seni, musyawarah besar, bazar dalam ruangan, dan expo UKM.',
  },
  {
    id: 'room-diskusi-library',
    name: 'Ruang Diskusi & Workshop Perpustakaan 2B',
    building: 'Gedung Perpustakaan Pusat Lt. 2',
    floor: 2,
    capacity: 20,
    facilities: ['Smart TV 55 Inch', 'Whiteboard Lebar', 'AC Split', 'Colokan Listrik Tiap Meja', 'Wi-Fi Eduroam Dedicated'],
    status: 'ACTIVE',
    openingHour: '08:30',
    closingHour: '16:30',
    imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    description: 'Ruang kedap suara untuk diskusi kelompok terfokus, bimbingan tugas akhir, dan rapat kerja kepanitiaan kecil.',
  },
];

// Helper to format ISO date string for today and tomorrow
const today = new Date();
const formatDateWithTime = (daysOffset: number, hours: number, minutes: number = 0) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysOffset);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
};

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'RB-202609-001',
    userId: 'usr-mhs1',
    roomId: 'room-auditorium',
    userName: 'Rizky Pratama',
    organization: 'BEM Universitas',
    startTime: formatDateWithTime(0, 9, 0),
    endTime: formatDateWithTime(0, 12, 0),
    purpose: 'Seminar Nasional Transformasi Digital Kampus 2026',
    participantCount: 200,
    additionalFacilities: '2 Pointer Wireless, 1 Mic Cadangan, Meja Registrasi Depan',
    notes: 'Mohon sound system dicek H-1 jam sebelum acara.',
    status: 'APPROVED',
    createdAt: formatDateWithTime(-2, 10, 0),
    updatedAt: formatDateWithTime(-1, 14, 0),
  },
  {
    id: 'RB-202609-002',
    userId: 'usr-dosen',
    roomId: 'room-smart-class',
    userName: 'Dr. Maya Anggraini',
    organization: 'Prodi Teknik Informatika',
    startTime: formatDateWithTime(0, 13, 0),
    endTime: formatDateWithTime(0, 15, 30),
    purpose: 'Kuliah Tamu Industri: Deep Learning in Healthcare',
    participantCount: 50,
    additionalFacilities: 'Kamera Hybrid streaming Zoom aktif',
    notes: 'Akan dihadiri dosen tamu dari University of Technology.',
    status: 'APPROVED',
    createdAt: formatDateWithTime(-1, 8, 30),
    updatedAt: formatDateWithTime(-1, 9, 15),
  },
  {
    id: 'RB-202609-003',
    userId: 'usr-mhs1',
    roomId: 'room-lab-ai',
    userName: 'Rizky Pratama',
    organization: 'Himpunan Mahasiswa Informatika (HMIF)',
    startTime: formatDateWithTime(1, 10, 0),
    endTime: formatDateWithTime(1, 13, 0),
    purpose: 'Bootcamp Hands-on Web Development Next.js & AI',
    participantCount: 40,
    additionalFacilities: 'Akses administrator pada PC Lab',
    notes: 'Peserta mahasiswa angkatan 2024 dan 2025.',
    status: 'PENDING',
    createdAt: formatDateWithTime(0, 8, 15),
    updatedAt: formatDateWithTime(0, 8, 15),
  },
  {
    id: 'RB-202609-004',
    userId: 'usr-staf',
    roomId: 'room-rapat-senat',
    userName: 'Hendra Gunawan',
    organization: 'Biro Administrasi Akademik',
    startTime: formatDateWithTime(1, 14, 0),
    endTime: formatDateWithTime(1, 16, 30),
    purpose: 'Rapat Koordinasi Persiapan Yudisium Semester Ganjil',
    participantCount: 22,
    additionalFacilities: 'Coffee break dan proyektor presentasi',
    notes: 'Dihadiri para Wakil Dekan Bidang Akademik.',
    status: 'PENDING',
    createdAt: formatDateWithTime(0, 8, 45),
    updatedAt: formatDateWithTime(0, 8, 45),
  },
  {
    id: 'RB-202609-005',
    userId: 'usr-mhs1',
    roomId: 'room-aula-student',
    userName: 'Rizky Pratama',
    organization: 'Unit Kegiatan Mahasiswa Seni',
    startTime: formatDateWithTime(-1, 15, 0),
    endTime: formatDateWithTime(-1, 18, 0),
    purpose: 'Gladi Bersih Festival Kebudayaan Mahasiswa',
    participantCount: 90,
    status: 'COMPLETED',
    createdAt: formatDateWithTime(-4, 9, 0),
    updatedAt: formatDateWithTime(-1, 18, 0),
  },
  {
    id: 'RB-202609-006',
    userId: 'usr-mhs1',
    roomId: 'room-diskusi-library',
    userName: 'Rizky Pratama',
    organization: 'Panitia Pemilu Raya Mahasiswa',
    startTime: formatDateWithTime(-2, 10, 0),
    endTime: formatDateWithTime(-2, 12, 0),
    purpose: 'Rapat Pleno Penetapan Calon Presma',
    participantCount: 15,
    status: 'REJECTED',
    notes: 'Ditolak karena ruangan telah dialokasikan untuk visitasi asesor BAN-PT.',
    createdAt: formatDateWithTime(-5, 11, 0),
    updatedAt: formatDateWithTime(-4, 16, 0),
  },
];

export const INITIAL_LOGS: ReservationLog[] = [
  {
    id: 'log-001',
    reservationId: 'RB-202609-001',
    adminId: 'usr-admin',
    adminName: 'Dr. Ir. Budi Santoso, M.Kom',
    previousStatus: 'PENDING',
    newStatus: 'APPROVED',
    reason: 'Pengajuan telah memenuhi persyaratan sarana dan tidak bentrok dengan agenda universitas.',
    createdAt: formatDateWithTime(-1, 14, 0),
  },
  {
    id: 'log-002',
    reservationId: 'RB-202609-002',
    adminId: 'usr-admin',
    adminName: 'Dr. Ir. Budi Santoso, M.Kom',
    previousStatus: 'PENDING',
    newStatus: 'APPROVED',
    reason: 'Kegiatan perkuliahan hibrida disetujui, teknisi audio visual telah ditugaskan.',
    createdAt: formatDateWithTime(-1, 9, 15),
  },
  {
    id: 'log-003',
    reservationId: 'RB-202609-006',
    adminId: 'usr-admin',
    adminName: 'Dr. Ir. Budi Santoso, M.Kom',
    previousStatus: 'PENDING',
    newStatus: 'REJECTED',
    reason: 'Ruangan perpustakaan sedang disterilkan untuk persiapan visitasi tim asesor akreditasi internasional.',
    createdAt: formatDateWithTime(-4, 16, 0),
  },
];

export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-1',
    userId: 'usr-mhs1',
    reservationId: 'RB-202609-001',
    title: 'Pengajuan Disetujui! 🎉',
    message: 'Reservasi Auditorium Utama untuk "Seminar Nasional Transformasi Digital" telah disetujui Administrator.',
    type: 'SUCCESS',
    isRead: false,
    createdAt: formatDateWithTime(-1, 14, 0),
  },
  {
    id: 'notif-2',
    userId: 'usr-mhs1',
    reservationId: 'RB-202609-006',
    title: 'Pengajuan Ditolak',
    message: 'Reservasi Ruang Diskusi Perpustakaan ditolak: "Ruangan sedang disterilkan untuk persiapan visitasi tim asesor".',
    type: 'DANGER',
    isRead: true,
    createdAt: formatDateWithTime(-4, 16, 0),
  },
  {
    id: 'notif-3',
    userId: 'usr-admin',
    reservationId: 'RB-202609-003',
    title: 'Pengajuan Baru Masuk',
    message: 'Rizky Pratama (HMIF) mengajukan peminjaman Lab Riset AI & Komputer untuk tanggal besok.',
    type: 'INFO',
    isRead: false,
    createdAt: formatDateWithTime(0, 8, 15),
  },
  {
    id: 'notif-4',
    userId: 'usr-admin',
    reservationId: 'RB-202609-004',
    title: 'Pengajuan Baru Masuk',
    message: 'Hendra Gunawan (BAAK) mengajukan peminjaman Ruang Rapat Senat untuk besok siang.',
    type: 'INFO',
    isRead: false,
    createdAt: formatDateWithTime(0, 8, 45),
  },
];
